### ISSUE TITLE
Minification task

### ISSUE THREAD

**Issue by JuhQ** [RamonGebben/Cquence#2]
You should have grunt/gulp here with minification tasks so that it'll be easier for other devs to contribute.
Now it seems that the minification is done manually using some unknown service/tool

**Comment by RamonGebben** [comment]
Thats a very good idea, cheers. I will include this tomorrow. Let's use today to discuss which tool to use.
Grunt or Gulp?

**Comment by JuhQ** [comment]
Both have equally good plugins for minification, usually the maintainers are the same people.

Use which ever you feel most comfortable with :)

**Comment by RamonGebben** [comment]
Then I would go for Gulp. This because the tasks are a lot more compact than in Grunt.

**Comment by jlengrand** [comment]
Can´t you do both?

I mean with minimal overlay between thm

**Comment by JuhQ** [comment]
I wouldn't recommend using both grunt and gulp in one project. Pick one and if it doesn't work out, switch to another.

Having two tools doing same thing will just add confusion and complexity, tasks changed in one will not be changed in the other (in the long run)

**Comment by RamonGebben** [comment]
@JuhQ +1 

@jlengrand I could add both tools and make 2 build files so to contributor can pick which one he/she wants to use.

**Comment by RamonGebben** [comment]
I just added the Gulp task. closing for now.
