### ISSUE TITLE
Namespace pollution

### ISSUE THREAD

**Issue by Searle** [RamonGebben/Cquence#3]
You should wrap the code:

```
(function() { <Cquence> })();
```

otherwise you're polluting the window namespace. Plus, the minifier will like that.

**Comment by RamonGebben** [comment]
Thats a very good idea. Since the main usecase of this project was to run in an iframe there was no need for it. Thanks for bringing it to my attention. Will fix.

**Comment by RamonGebben** [comment]
Fixed this.
